spring.application.name=backend-vehicular
server.port=8081

# --- database connection (postgresql basado en tu imagen) ---
# la url usa el puerto 5432 y el nombre de la base de datos de la captura
spring.datasource.url=jdbc:postgresql://localhost:5432/LavaRapido_Vehicular
spring.datasource.username=postgres
spring.datasource.password=Stiven2025*

# driver especifico para postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# --- hibernate jpa ---
# crea o actualiza las tablas automaticamente
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# dialecto correcto para hablar el lenguaje de postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# llave secreta para firmar los tokens jwt - debe tener al menos 32 caracteres para el algoritmo hs256
jwt.secret=mi_clave_secreta_super_larga_de_prueba_123
logging.level.org.springframework.security=TRACE


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=weqwew542@gmail.com
spring.mail.password=omftwmlvtrbolvtz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL del frontend para armar el enlace en el correo
app.frontend.url=http://localhost:5173